name: Deployment to production environment
on: 
    push:
       branches:
            - production
    workflow_dispatch:

env:
    SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  deploy-review:
    name: Deploying to production environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
            ref: ${{ github.ref }}

    - name: 'Create private key file'
      run: echo "${{ secrets.PRIVATE_KEY }}" > ./private_key && chmod 600 ./private_key

    - name: Setup SSH connection
      run: >
        echo '#!/bin/sh' >> ./passphrase_script.sh &&
        echo "echo ${{ secrets.PASSPHRASE }}" >> ./passphrase_script.sh &&
        chmod +x ./passphrase_script.sh

    - run: ssh-agent -a $SSH_AUTH_SOCK > /dev/null
    - run: DISPLAY=1 SSH_ASKPASS='./passphrase_script.sh' ssh-add ./private_key < /dev/null

    - name: Executing git pull to remote build directory and run build command
      run: >
        ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} -o StrictHostKeyChecking=no
        "cd ${{ secrets.REMOTE_PATH_BUILD }}/ && 
        git pull https://Coup-Critique:${{ secrets.GITHUB_TOKEN }}@github.com/Coup-Critique/coupcritique-front.git main &&
        npm run build"

    - name: Override actual build directory
      run: >
        ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} -o StrictHostKeyChecking=no
        "cd ${{ secrets.REMOTE_PATH }}/ && cp -r ${{ secrets.REMOTE_PATH_BUILD }}/.next . && pm2 restart next"
